from collections.abc import Callable

class BaseTarget:
    multipart_filename: str | None
    multipart_content_type: str | None
    def __init__(self, validator: Callable[[bytes], None] | None = ...) -> None: ...
    def start(self) -> None: ...
    def on_start(self) -> None: ...
    def data_received(self, chunk: bytes) -> None: ...
    def on_data_received(self, chunk: bytes) -> None: ...
    def finish(self) -> None: ...
    def on_finish(self) -> None: ...
    async def astart(self) -> None: ...
    async def on_start_async(self) -> None: ...
    async def adata_received(self, chunk: bytes) -> None: ...
    async def on_data_received_async(self, chunk: bytes) -> None: ...
    async def afinish(self) -> None: ...
    async def on_finish_async(self) -> None: ...
    def set_multipart_filename(self, filename: str) -> None: ...
    def set_multipart_content_type(self, content_type: str) -> None: ...
